### ISSUE TITLE
Ability to spawn multiple escorts?

### ISSUE THREAD

**Issue by MrFinny60** [xesdoog/Billionaire-Script#2]
Hello, I like your script, is there a possibility to spawn multiple escorts? I get that it would get pretty packed when they follow you, but can you make them follow eachother in a line then? Didn't know how to contact you, so I hope you see this.

**Comment by xesdoog** [comment]
Hello Finny,

The way this script was designed is to spawn one group of bodyguards and one group of escorts and keep track of them. 
The "following you" part is not the issue but GTA has a limit of how many pedestrians can be in your group, ie: act as bodyguards. With that in mind along with the fact that this script works online, we have to leave room for other scripts and the game itself to add more peds to your group. GTA does that in some online missions/activities and if we choke the limit we will either brake this script, other scripts or the game.
