### ISSUE TITLE
Add helicopter service?

### ISSUE THREAD

**Issue by Purple-Palm** [xesdoog/Billionaire-Script#4]
It would be great to add a helicopter service, just like with merryweather helicopter pickup, but with swift deluxe helicopter and some other features. It would be great so I can do everything from yimmenu, so Im not having to wait for merryweather to answer the phone and pick me up on a shitty helicopter.

**Comment by xesdoog** [comment]
Okay I'll probably do it this weekend.
Btw, If you want a luxury helicopter pickup, the CEO vehicle requests has one with champagne in the back and everything. The downside is that it costs $5k even if you own a SuperVolito and it can not land. It can only fly to a waypoint and hover over it or fly you to one of your CEO businesses with the option to teleport there.
I'll do one similar but it will spawn right in front of you and will be able to land anywhere, teleport to several locations and will cost exactly $0.

**Comment by xesdoog** [comment]
@Purple-Palm Feature added in [0.4.5](https://github.com/xesdoog/Billionaire-Script/commit/299f456126ed9ff7edce52f1da0241342a4172ff) 
I forgot to close the issue with the commit message 💀

*closing as completed*
